name: Build and Deploy

on:
  push:
    branches:
      - master  # or the branch you want to trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install JDK 22
        run: |
          # Download JDK 22 (update URL if necessary)
          wget https://download.oracle.com/java/22/latest/jdk-22_linux-x64_bin.tar.gz
          # Extract the JDK
          tar -xzf jdk-22_linux-x64_bin.tar.gz
          # Set up JAVA_HOME
          echo "JAVA_HOME=$(pwd)/jdk-22" >> $GITHUB_ENV
          echo "$JAVA_HOME/bin" >> $PATH

      - name: Build JAR file
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t sample-app:latest .

      - name: Push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag sample-app:latest $DOCKER_USERNAME/sample-app:latest
          docker push $DOCKER_USERNAME/sample-app:latest
        # Replace $DOCKER_USERNAME and $DOCKER_PASSWORD with your Docker Hub credentials

