name: Build and Deploy

on:
  push:
    branches:
      - master  # or the branch you want to trigger this workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          java-version: '22'

      - name: Build JAR file
        run: mvn clean package

      - name: Build Docker image
        run: |
          docker build -t sample-app:latest .

      - name: Push Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag sample-app:latest $DOCKER_USERNAME/sample-app:latest
          docker push $DOCKER_USERNAME/sample-app:latest
        # Replace $DOCKER_USERNAME and $DOCKER_PASSWORD with your Docker Hub credentials

